### tabula-py

In [ ]:
!pip -qqq install tabula-py

In [1]:
# import required dependencies
import pandas as pd
import numpy as np
import tabula

In [11]:
file_path = "C:/Users/65814/OneDrive - National University of Singapore (1)/Tools/PDF_DataExtraction/data/invoice.pdf" 
dfs = tabula.read_pdf(file_path, pages='all', multiple_tables=True, stream=True)

Got stderr: Jun 09, 2024 10:04:52 AM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: inherited resources of source document are not imported to destination page
Jun 09, 2024 10:04:52 AM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: call importedPage.setResources(page.getResources()) to do this
Jun 09, 2024 10:04:53 AM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: inherited resources of source document are not imported to destination page
Jun 09, 2024 10:04:53 AM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: call importedPage.setResources(page.getResources()) to do this

In [7]:
# check number of tables extracted from the pdf document
print(len(dfs))

2

In [9]:
# view tables extracted from the dcoument
for df in dfs:
    display(df)

,Description,Quantity,Unit Price,Discount(%),Tax,Amount SGD
0,[230428FN-001] One-click sanger sequencing,4.0,4.6,NaN,8%,18.40
1,[230428FN-001] PCR product Sequencing,5.0,4.6,NaN,8%,23.00
2,[230428FN-002] One-click sanger sequencing,3.0,4.6,NaN,8%,13.80
3,[230428FN-002] PCR product Sequencing,3.0,4.6,NaN,8%,13.80
4,[230502FN-004] PCR product Sequencing,78.0,4.6,NaN,8%,358.80
5,[230502FN-015] PCR product Sequencing,10.0,4.6,NaN,8%,46.00
6,[230504FN-001] PCR product Sequencing,20.0,4.6,NaN,8%,92.00
7,[230504FN-004] PCR product Sequencing,2.0,4.6,NaN,8%,9.20
8,[230505FN-001] PCR product Sequencing,30.0,4.6,NaN,8%,138.00
9,[230508FN-001] PCR product Sequencing,8.0,4.6,NaN,8%,36.80
10,[230508FN-002] PCR product Sequencing,30.0,4.6,NaN,8%,138.00
11,[230509FN-001] PCR product Sequencing,40.0,4.6,NaN,8%,184.00
12,[230510FN-001] PCR product Sequencing,8.0,4.6,NaN,8%,36.80
13,[230510FN-007] PCR product Sequencing,18.0,4.6,NaN,8%,82.80
14,[230510FN-020] PCR product Sequencing,4.0,4.6,NaN,8%,18.40
15,[230512FN-001] PCR product Sequencing,16.0,4.6,NaN,8%,73.60
16,[230515FN-001] PCR product Sequencing,12.0,4.6,NaN,8%,55.20
17,[230516FN-002] PCR product Sequencing,12.0,4.6,NaN,8%,55.20
18,[230516FN-015] PCR product Sequencing,36.0,4.6,NaN,8%,165.60
19,[230522FN-001] PCR product Sequencing,8.0,4.6,NaN,8%,36.80
20,NaN,NaN,NaN,NaN,Subtotal,"1,596.20"

  Total Local supply of goods and services 8%    127.68
0                           Invoice Total SGD  1,723.88
1                      Total Net Payments SGD  1,723.88
2                              Amount Due SGD      0.00